# Use an official OpenJDK runtime as a base image
FROM eclipse-temurin:17-jdk-jammy
# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from target/ folder to the container
COPY target/docker-demo.jar app.jar

# Expose the application port (Spring Boot default is 8080)
EXPOSE 8080

# Command to run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]